export const COLLECTION_DEFINITIONS = {
  'home-hero': {
    label: 'Accueil — Section héro',
    type: 'singleton',
    defaultSlug: 'principal',
    entryTitleField: 'title',
    fields: [
      { name: 'badge', label: 'Badge', type: 'text', required: true },
      { name: 'title', label: 'Titre', type: 'text', required: true },
      { name: 'lead', label: 'Texte introductif', type: 'textarea', required: true },
      { name: 'primaryCtaLabel', label: 'Libellé CTA principal', type: 'text', required: true },
      { name: 'primaryCtaHref', label: 'Lien CTA principal', type: 'text', required: true },
      { name: 'secondaryCtaLabel', label: 'Libellé CTA secondaire', type: 'text' },
      { name: 'secondaryCtaHref', label: 'Lien CTA secondaire', type: 'text' },
      {
        name: 'illustrationPath',
        label: 'Image héro (chemin relatif depuis /public)',
        type: 'image',
        helpText: "Cliquez sur 'Choisir le fichier' pour téléverser une image.",
        cropAspect: 4 / 3,
      },
    ],
  },
  'quick-links': {
    label: 'Accueil — Liens rapides',
    type: 'collection',
    entryTitleField: 'title',
    fields: [
      { name: 'icon', label: 'Icône Remix (classe)', type: 'text', placeholder: 'ri-trophy-line' },
      { name: 'title', label: 'Titre', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea', required: true },
      { name: 'href', label: 'Lien', type: 'text', required: true },
    ],
  },
  partners: {
    label: 'Accueil — Partenaires',
    type: 'collection',
    entryTitleField: 'name',
    fields: [
      { name: 'name', label: 'Nom', type: 'text', required: true },
      { name: 'url', label: 'Lien externe', type: 'text' },
      {
        name: 'logoPath',
        label: 'Logo (chemin relatif)',
        type: 'image',
        placeholder: '/assets/logo.png',
        required: true,
        helpText: "Cliquez sur 'Choisir le fichier' pour téléverser un logo.",
        cropAspect: 3 / 1,
      },
    ],
  },
  palmares: {
    label: 'Palmarès',
    type: 'collection',
    entryTitleField: 'title',
    fields: [
      { name: 'year', label: 'Année', type: 'text', required: true },
      { name: 'title', label: 'Titre', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea', required: true },
      { name: 'location', label: 'Lieu', type: 'text' },
    ],
  },
  timeline: {
    label: 'Historique — Événements',
    type: 'collection',
    entryTitleField: 'title',
    fields: [
      { name: 'year', label: 'Année', type: 'text', required: true },
      { name: 'title', label: 'Titre', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea', required: true },
      {
        name: 'imagePath',
        label: 'Image (chemin relatif)',
        type: 'image',
        placeholder: '/assets/historique-photos/2013.jpg',
        helpText: "Cliquez sur 'Choisir le fichier' pour téléverser une image.",
        cropAspect: 3 / 2,
      },
      { name: 'imageAlt', label: "Texte alternatif de l'image", type: 'text' },
    ],
  },
  'events-upcoming': {
    label: 'Calendrier — À venir',
    type: 'collection',
    entryTitleField: 'title',
    fields: [
      { name: 'title', label: 'Titre', type: 'text', required: true },
      { name: 'summary', label: 'Résumé', type: 'textarea', required: true },
      { name: 'date', label: 'Date (texte libre)', type: 'text' },
      { name: 'ctaLabel', label: 'Texte du bouton', type: 'text', required: true },
      {
        name: 'ctaHref',
        label: 'Lien du bouton',
        type: 'text',
        required: true,
        placeholder: '/calendrier/mon-evenement',
      },
      {
        name: 'imagePath',
        label: 'Image',
        type: 'image',
        placeholder: '/assets/...',
        helpText: "Cliquez sur 'Choisir le fichier' pour téléverser une image.",
        cropAspect: 3 / 2,
      },
    ],
  },
  'events-past': {
    label: 'Calendrier — Passés',
    type: 'collection',
    entryTitleField: 'title',
    fields: [
      { name: 'title', label: 'Titre', type: 'text', required: true },
      { name: 'summary', label: 'Résumé', type: 'textarea', required: true },
      { name: 'date', label: 'Date (texte libre)', type: 'text' },
      { name: 'ctaLabel', label: 'Texte du bouton', type: 'text', required: true },
      {
        name: 'ctaHref',
        label: 'Lien du bouton',
        type: 'text',
        required: true,
        placeholder: '/calendrier/mon-evenement',
      },
      {
        name: 'imagePath',
        label: 'Image',
        type: 'image',
        placeholder: '/assets/...',
        helpText: "Cliquez sur 'Choisir le fichier' pour téléverser une image.",
        cropAspect: 3 / 2,
      },
    ],
  },
  'event-detail': {
    label: 'Calendrier — Fiches détail',
    type: 'collection',
    entryTitleField: 'title',
    fields: [
      { name: 'title', label: 'Titre', type: 'text', required: true },
      { name: 'intro', label: 'Accroche', type: 'textarea' },
      {
        name: 'bodyHtml',
        label: 'Contenu',
        type: 'textarea',
        required: true,
        autoParagraphs: true,
        richText: true,
        helpText: 'Mise en forme disponible (gras, italique, couleur).',
      },
      { name: 'stats_students', label: "Nombre d'étudiants (Stats)", type: 'text', placeholder: '400+' },
      { name: 'stats_years', label: "Années d'existence (Stats)", type: 'text', placeholder: '20+' },
      {
        name: 'imagePath',
        label: 'Image',
        type: 'image',
        placeholder: '/assets/...',
        helpText: "Cliquez sur 'Choisir le fichier' pour téléverser une image.",
        cropAspect: 3 / 2,
      },
    ],
  },
  'gallery-slides': {
    label: 'Galerie — Slides',
    type: 'collection',
    entryTitleField: 'altText',
    fields: [
      {
        name: 'imagePath',
        label: 'Image',
        type: 'image',
        placeholder: '/assets/vehicule1.jpg',
        required: true,
        helpText: "Cliquez sur 'Choisir le fichier' pour téléverser une image.",
        cropAspect: 2 / 1,
      },
      { name: 'altText', label: 'Texte alternatif', type: 'text' },
    ],
  },
  vehicles: {
    label: 'Véhicules',
    type: 'collection',
    entryTitleField: 'title',
    fields: [
      { name: 'category', label: 'Catégorie', type: 'text', placeholder: 'Urban Concept / Prototype' },
      { name: 'title', label: 'Titre', type: 'text', required: true },
      { name: 'intro', label: 'Introduction', type: 'textarea', required: true },
      {
        name: 'bodyHtml',
        label: 'Texte détaillé',
        type: 'textarea',
        autoParagraphs: true,
        richText: true,
        helpText: 'Mise en forme disponible (gras, italique, couleur).',
      },
      { name: 'stats_students', label: "Nombre d'étudiants (Stats)", type: 'text', placeholder: '400+' },
      { name: 'stats_years', label: "Années d'existence (Stats)", type: 'text', placeholder: '20+' },
      {
        name: 'imagePath',
        label: 'Image principale',
        type: 'image',
        placeholder: '/assets/vehicule1.jpg',
        helpText: "Cliquez sur 'Choisir le fichier' pour téléverser une image.",
        cropAspect: 3 / 2,
      },
      {
        name: 'galleryPaths',
        label: 'Galerie photos',
        type: 'gallery',
        placeholder: '',
        helpText: "Téléversez plusieurs images pour la galerie.",
      },
    ],
  },
  'page-presentation': {
    label: 'Page — Présentation',
    type: 'singleton',
    defaultSlug: 'association',
    entryTitleField: 'title',
    fields: [
      { name: 'title', label: 'Titre', type: 'text', required: true },
      {
        name: 'bodyHtml',
        label: 'Contenu',
        type: 'textarea',
        required: true,
        autoParagraphs: true,
        richText: true,
        helpText: 'Mise en forme disponible (gras, italique, couleur).',
      },
      { name: 'stats_students', label: "Nombre d'étudiants (Stats)", type: 'text', placeholder: '400+' },
      { name: 'stats_years', label: "Années d'existence (Stats)", type: 'text', placeholder: '20+' },
      { name: 'showTeamSection', label: 'Afficher la section Équipe', type: 'boolean', helpText: 'Activez pour afficher les membres de l\'équipe en bas de page.' },
      {
        name: 'teamMembers',
        label: 'Membres de l\'équipe',
        type: 'team-list',
        helpText: 'Ajoutez les membres ici.',
      },
    ],
  },
};

export function getCollectionDefinition(collection) {
  return COLLECTION_DEFINITIONS[collection] || null;
}

export const MANAGED_COLLECTIONS = Object.keys(COLLECTION_DEFINITIONS);
